config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'items#index'

  resources :items do
    resources :comments, only: :create
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :index do
      collection do
        put 'pay', to: 'purchases#pay'
      end
    end
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :users, only: :show
  resources :my_pages, only: :index
  resources :categories, only: :show
  resources :brands, only: :index
  resources :credit_cards, only: :new do
    collection do
      post 'pay', to: 'credit_cards#pay'
      delete 'delete', to: 'credit_cards#delete'
      get 'show', to: 'credit_cards#show'
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  get '*path', controller: 'application', action: 'render_404'
  get '*path', controller: 'application', action: 'render_500'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  has_ancestry
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :item
  validates :content, presence: true
end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true
  validates :card_id, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :item_images, dependent: :destroy
  has_many :user_rates, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :size, optional: true
  belongs_to :buyer, class_name: "User", optional: true
  accepts_nested_attributes_for :item_images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :item_status
  belongs_to_active_hash :item_delivery_fee
  belongs_to_active_hash :item_delivery_method
  belongs_to_active_hash :item_prefecture
  belongs_to_active_hash :item_preparation_day
  
  with_options presence: true do
    validates :name
    validates :price,numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
    validates :status
    validates :delivery_method
    validates :delivery_from_location
    validates :item_explanation
    validates :preparation_day
    validates :delivery_fee
  end
end

app/models/item_delivery_fee.rb
class ItemDeliveryFee < ActiveHash::Base
  self.data = [
    {id: 1, payer: "送料込み（出品者負担）"}, {id: 2, payer: "着払い（購入者負担）"}
  ]
end

app/models/item_image.rb
class ItemImage < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :item

  mount_uploader :image, ImageUploader
end

app/models/item_prefecture.rb
class ItemPrefecture < ActiveHash::Base
  self.data = [
    {id: 1, name: '北海道'}, {id: 2, name: '青森県'}, {id: 3, name: '岩手県'},
    {id: 4, name: '宮城県'}, {id: 5, name: '秋田県'}, {id: 6, name: '山形県'},
    {id: 7, name: '福島県'}, {id: 8, name: '茨城県'}, {id: 9, name: '栃木県'},
    {id: 10, name: '群馬県'}, {id: 11, name: '埼玉県'}, {id: 12, name: '千葉県'},
    {id: 13, name: '東京都'}, {id: 14, name: '神奈川県'}, {id: 15, name: '新潟県'},
    {id: 16, name: '富山県'}, {id: 17, name: '石川県'}, {id: 18, name: '福井県'},
    {id: 19, name: '山梨県'}, {id: 20, name: '長野県'}, {id: 21, name: '岐阜県'},
    {id: 22, name: '静岡県'}, {id: 23, name: '愛知県'}, {id: 24, name: '三重県'},
    {id: 25, name: '滋賀県'}, {id: 26, name: '京都府'}, {id: 27, name: '大阪府'},
    {id: 28, name: '兵庫県'}, {id: 29, name: '奈良県'}, {id: 30, name: '和歌山県'},
    {id: 31, name: '鳥取県'}, {id: 32, name: '島根県'}, {id: 33, name: '岡山県'},
    {id: 34, name: '広島県'}, {id: 35, name: '山口県'}, {id: 36, name: '徳島県'},
    {id: 37, name: '香川県'}, {id: 38, name: '愛媛県'}, {id: 39, name: '高知県'},
    {id: 40, name: '福岡県'}, {id: 41, name: '佐賀県'}, {id: 42, name: '長崎県'},
    {id: 43, name: '熊本県'}, {id: 44, name: '大分県'}, {id: 45, name: '宮崎県'},
    {id: 46, name: '鹿児島県'}, {id: 47, name: '沖縄県'}
  ]
end

app/models/item_status.rb
class ItemStatus < ActiveHash::Base
  self.data = [
    {id: 1, status: "新品、未使用"}, {id: 2, status: "未使用に近い"}, {id: 3, status: "目立った傷や汚れなし"}, 
    {id: 4, status: "やや傷や汚れあり"}, {id: 5, status: "傷や汚れあり"}, {id: 6, status: "全体的に状態が悪い"}
  ]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :item_prefecture

  with_options presence: true do
    validates :post_code
    validates :prefecture_id
    validates :city
    validates :address
  end

  mount_uploader :image, ImageUploader
end

app/models/size.rb
class Size < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :email
    validates :password
    validates :password_confirmation
    validates :family_name
    validates :first_name
    validates :family_name_kana
    validates :first_name_kana
    validates :birth_day
  end
  
  has_many :comments, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_items, through: :likes, source: :item
  has_many :user_rates
  has_one :profile, dependent: :destroy
  has_one :credit_card, dependent: :destroy
  # accepts_nested_attributes_for :profile

  def already_liked?(item)
    likes.exists?(item_id: item.id)
  end
end

app/models/user_rate.rb
class UserRate < ApplicationRecord
  belongs_to :user
  belongs_to :item
end

app/controllers/my_pages_controller.rb
class MyPagesController < ApplicationController
  before_action :move_to_index, only: :index
  
  def index
    @user = current_user
    @profile = Profile.find_by(user_id: @user.id)
    @rates = UserRate.where(user_id: @user.id).length
    @items = Item.where(user_id: @user.id).length
  end

  private

  def move_to_index
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/my_pages_helper.rb
module MyPagesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/my_pages/_items_list.html.haml
%section.mypage-tab-items
  %h2.mypage-tab-head
    購入した商品
  %ul.mypage-tabs
    %li.active
      %h3
        = link_to "取引中", "#"
    %li
      %h3
        = link_to "過去の取引", "#"
  .tab-content
    %ul#mypage-tab.items.ongoing.active
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "テストさんからコメントがあります"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "テストさんからコメントがあります"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li.mypage-go-list
        = link_to "一覧を見る", "#"

    %ul#mypage-tab.items.done
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "取引が完了しました"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "取引が完了しました"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li.mypage-go-list
        = link_to "一覧を見る", "#"

app/views/my_pages/_notification_todo_list.html.haml
%section.mypage-tab-notification-todo
  %ul.mypage-tabs
    %li.active
      %h3
        = link_to "お知らせ", "#"
    %li
      %h3
        = link_to "やることリスト", "#"
  .tab-content
    %ul#mypage-tab.notification-todo.notification.active
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "事務局からおしらせがあります"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "事務局からおしらせがあります"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li.mypage-go-list
        = link_to "一覧を見る", "#"
    %ul#mypage-tab.notification-todo.todo
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "商品を発送してください"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li
        = link_to "#" do
          %figure
            = image_tag('member_photo_noimage_thumb.png',  height: '30px', width: '30px', class: "list-icon")
          .mypage-item-body
            .message-item
              = "商品を発送してください"
            .message-time-before
              = icon('far', 'clock', class: "clock-icon")
              %span 1時間前
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li.mypage-go-list
        = link_to "一覧を見る", "#"
          

app/views/my_pages/_side_bar.html.haml
.mypage-side-bar
  %nav.mypage-nav
    %ul.mypage-nav-list
      %li
        = link_to my_pages_path, class: "list-item-head" do
          マイページ
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li 
        = link_to "#", class: "list-item" do
          お知らせ
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %li
        = link_to "#", class: "list-item" do
          やることリスト
          = icon('fas', 'chevron-right', class: "arrow-icon") 
      %li
        = link_to likes_path, class: "list-item" do
          お気に入り一覧
          = icon('fas', 'chevron-right', class: "arrow-icon") 
      %li
        = link_to "#", class: "list-item" do
          出品する
          = icon('fas', 'chevron-right', class: "arrow-icon")
      %h3.mypage-nav-head
        設定
    %ul.mypage-nav-list
      %li
        - if current_user.profile
          = link_to edit_profile_path(current_user.id), class: "list-item" do
            プロフィール情報
            = icon('fas', 'chevron-right', class: "arrow-icon")
        - else
          = link_to new_profile_path, class: "list-item" do
            プロフィール情報
            = icon('fas', 'chevron-right', class: "arrow-icon")
      %li
        = link_to credit_cards_path, class: "list-item" do
          支払い方法
          = icon('fas', 'chevron-right', class: "arrow-icon")

app/views/my_pages/index.html.haml
.mypage-container.clearfix
  .mypage-main-content
    %section.mypage-user-icon
      = link_to my_pages_path do
        .mypage-user-photo
          - if @profile&.image.blank?
            = image_tag('member_photo_noimage_thumb.png', height: '60px', width: '60px')
          - else
            = image_tag "#{@profile.image.url}", class: "profile-image", height: '60px', width: '60px'
        %h2.user-name
          = @user.nickname
        .mypage-score
          %span
            = "評価  #{@rates}"
          %span
            = "出品数  #{@items}"
    = render "notification_todo_list"

    = render "items_list"
  
  = render partial: 'side_bar', locals: {card: @card}

= link_to new_item_path, class: "sell-btn" do
  %div 出品する
  = image_tag "icon_camera.png", size: "54x54", class: "camera-icon"