config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'items#index'

  resources :items do
    resources :comments, only: :create
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    resources :purchases, only: :index do
      collection do
        put 'pay', to: 'purchases#pay'
      end
    end
  end
  resources :likes, only: [:index, :create, :destroy]
  resources :users, only: :show
  resources :my_pages, only: :index
  resources :categories, only: :show
  resources :brands, only: :index
  resources :credit_cards, only: :new do
    collection do
      post 'pay', to: 'credit_cards#pay'
      delete 'delete', to: 'credit_cards#delete'
      get 'show', to: 'credit_cards#show'
    end
  end
  resources :profiles, only: [:new, :create, :edit, :update]
  get '*path', controller: 'application', action: 'render_404'
  get '*path', controller: 'application', action: 'render_500'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :item_images, dependent: :destroy
  has_many :user_rates, dependent: :destroy
  belongs_to :user
  belongs_to :category
  belongs_to :size, optional: true
  belongs_to :buyer, class_name: "User", optional: true
  accepts_nested_attributes_for :item_images, allow_destroy: true

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :item_status
  belongs_to_active_hash :item_delivery_fee
  belongs_to_active_hash :item_delivery_method
  belongs_to_active_hash :item_prefecture
  belongs_to_active_hash :item_preparation_day
  
  with_options presence: true do
    validates :name
    validates :price,numericality: {only_integer: true, greater_than_or_equal_to: 300, less_than_or_equal_to: 9999999}
    validates :status
    validates :delivery_method
    validates :delivery_from_location
    validates :item_explanation
    validates :preparation_day
    validates :delivery_fee
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  before_action :set_item, only: [:edit, :update]
  before_action :move_to_index, only: [:edit]
  before_action :move_to_index_second, only: [:new, :create]
  
  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end
  
  def get_category_grandchildren
    child_id = child_params[:child_id]
    @category_grandchildren = Category.find(child_id).children 
  end

  def index
    @items = Item.includes(:item_images).order("id DESC").limit(3)
    @items_brand = Item.where(brand: "nike").includes(:item_images).order("id DESC").limit(3)
  end

  def new
    @item = Item.new
    @item.item_images.new
    @category_parent_array = Category.where(ancestry: nil)
  end

  def create
    @item = Item.new(item_params)
    if item_params[:item_images_attributes]
      if @item.save
        redirect_to root_path
      else
        redirect_to new_item_path
      end
    else
      redirect_to new_item_path
    end
  end

  def edit
    @category_parent_array = Category.where(ancestry: nil)
    @item_images = ItemImage.where(item_id: @item.id)
    @category_grandchild = Category.find(@item.category_id)
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    @category_children = Category.find(@category_parent.id).children
    @category_grandchildren = Category.find(@category_child.id).children
  end

  def update
    @item_images = ItemImage.where(item_id: @item.id)
    image_form_count = item_params_update[:item_images_attributes].to_hash.length
    image_count = @item_images.length
    delete_image_count = 0
    count = 0
    while count < image_count do
      if item_params_update[:item_images_attributes].values[count][:"_destroy"] == "1"
        delete_image_count += 1
      end
      count += 1
    end

    if delete_image_count != image_count || image_form_count != image_count
      @item.update(item_params_update)
      redirect_to root_path
    else
      redirect_to edit_item_path(params[:id])
    end
  end

  def show
    @item = Item.find(params[:id])
    @images = @item.item_images
    @image = @images.first
    @category_grandchild = Category.find(@item.category_id)
    @category_child = @category_grandchild.parent
    @category_parent = @category_child.parent
    @comment = Comment.new
    @comments = @item.comments.includes(:user)
    @like = Like.new
  end

  def destroy
    item = Item.find(params[:id])
    if user_signed_in? && item.user_id == current_user.id && item.destroy
      redirect_to root_path
    else
      render "show"
    end
  end

  private

  def child_params
    params.permit(:child_id)
  end
  
  def item_params
    category_id = params.permit(:category_id)
    params.require(:item).permit(:name, :price, :item_explanation, :status, :brand, :delivery_fee, :delivery_method, :delivery_from_location, :preparation_day, :price, item_images_attributes: [:image]).merge(user_id: current_user.id).merge(category_id)
  end

  def item_params_update
    category_id = params.permit(:category_id)
    params.require(:item).permit(:name, :price, :item_explanation, :status, :brand, :delivery_fee, :delivery_method, :delivery_from_location, :preparation_day, :price, item_images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id).merge(category_id)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def move_to_index
    redirect_to root_path unless user_signed_in? && @item.user_id == current_user.id
  end

  def move_to_index_second
    redirect_to root_path unless user_signed_in?
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_brand.html.haml
- items.each do |item|
  .menu5__item_box__items__item
    = link_to item_path(item.id) do
      .images
        = image_tag item.item_images[0].image.url, class: "images__image"
        - if item.buyer_id.present?
          .sold-tag
            .sold-tag__title sold out
      .box
        %h3.box__title
          = item.name
        .box__content
          %ul
            %li
              = item.price
            %li
              = icon('far','heart', class: 'icon')
              ０
          %p (税込)

app/views/items/_category.html.haml
- items.each do |item|
  .menu5__item_box__items__item
    = link_to item_path(item.id) do
      .images
        = image_tag item.item_images[0].image.url, class: "images__image"
        - if item.buyer_id.present?
          .sold-tag
            .sold-tag__title sold out
      .box
        %h3.box__title
          = item.name
        .box__content
          %ul
            %li
              = item.price
            %li
              = icon('far','heart', class: 'icon')
              ０
          %p (税込)
    

app/views/items/_footer.html.haml
.footer_banner
  .inner
    %h2 だれでもかんたん、人生を変えるフリマアプリ
    %p 今すぐ無料ダウンロード！
    .menu1__content__btn
      = link_to "#" do
        = image_tag('app-store-logo.svg', height: '80px', width: '180px', class: 'app-store-logo')
      = link_to "#" do
        = image_tag('google-play-logo.svg', height: '80px', width: '180px', class: 'google-play-logo')
.footer
  %ul.footer__content
    %li.footer__content__menu
      %h2 FURIMAについて
      %ul
        %li
          = link_to "会社概要(運営会社)","#"
        %li
          = link_to "プライバシーポリシー","#"
        %li
          = link_to "FURIMA利用規約","#"
        %li
          = link_to "ポイントに関する特約","#"
    %li.footer__content__menu
      %h2 FURIMAを見る
      %ul
        %li
          = link_to "カテゴリー一覧","#"
        %li
          = link_to "ブランド一覧","#"
    %li.footer__content__menu
      %h2 ヘルプ＆ガイド
      %ul
        %li
          = link_to "FURIMAガイド","#"
        %li
          = link_to "FURIMAロゴ利用ガイド","#"
        %li
          = link_to "お知らせ","#"
  .footer_logo
    = link_to image_tag('logo-white.png',  height: '40px', width: '140px', class: 'header__content__menu__title'),root_path
  %p © FURIMA

app/views/items/_form.html.haml
.items-new-wrapper
  .form__area
    = form_for item do |form|
      .form__content__image
        %h5.form__title
          出品画像
        %span.required__text
          必須
        .form-box
          %h3.form__box__image
            最大10枚までアップロードできます
        .form__box__area#image-box
          #previews
            - if item.persisted?
              - item_images.each_with_index do |image, idx|
                .new-wrapper__main__preview__image
                  = image_tag image.image.url, data:{ index: idx }, width: "131", height: '160'
                  .edit-btn
                    = icon('far', 'times-circle', class: "delete-icon", data:{ index: idx })
                    %span{ data: {index: "#{idx}"} }
          %label{id: "image-wrapper", action: request.path}
            .new-wrapper__main__image-field
              .new-wrapper__main__image-field__texts
                %i{class: "fas fa-camera",id: "camera-icon"}
                クリックしてファイルをアップロード
              = form.fields_for :item_images do |i|
                .js-file-group{ data: {index: "#{i.index}"} }
                  = i.file_field :image, {class: "js-file"}
                - if item.persisted?
                  = i.check_box :_destroy, data:{ index: i.index }, class: "hidden-destroy"
              - if item.persisted?
                .js-file-group{ data: {index: "#{item_images.count}"} }
                  = file_field_tag :item, name: "item[item_images_attributes][#{item_images.count}][image]", class: 'js-file', id: "item_item_images_attributes_#{item_images.count}_image"
        .form__content
          %h5.form__title
            商品名
          %span.required__text
            必須
          .items-new__page__main__name__form
            = form.text_field :name, placeholder: "40文字まで", class: "items-new__page__main__name__form__bar"
        .form__content
          %h5.form__title
            商品説明
          %span.required__text
            必須
          .items-new__page__main__explanation__form
            = form.text_area :item_explanation, placeholder: "商品の説明(必須 1,000文字以内)(色、素材、重さ、定価、注意点など)例)2010年頃に一万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "items-new__page__main__name__form__bar"
          .text__count
            %span 0/1000
        .form__detail
          商品の詳細
        .listing-form-box
          .listing-product-detail__category
            = form.label 'カテゴリー', class: 'listing-default__label'
            %span.required__text
              必須
            - if item.category_id.nil?
              .listing-select-wrapper
                .listing-select-wrapper__box
                  .listing-select-wrapper__box--select
                    = form.collection_select :category_id, category_parent_array, :id, :name, prompt: "---"
                    .arrow-icon
                      = icon('fas', 'chevron-down', class: "arrow-icon")
            - else
              .listing-select-wrapper
                .listing-select-wrapper__box
                  .listing-select-wrapper__box--select
                    = form.collection_select :category_id, category_parent_array, :id, :name, prompt: "---", selected: category_parent
                    .arrow-icon
                      = icon('fas', 'chevron-down', class: "arrow-icon")
              .listing-select-wrapper__added#children_wrapper
                .listing-select-wrapper__box
                  .listing-select-wrapper__box--select
                    = form.collection_select :category_id, category_children, :id, :name, prompt: "---", selected: category_child
                    .arrow-icon
                      = icon('fas', 'chevron-down', class: "arrow-icon")
              .listing-select-wrapper__added#grandchildren_wrapper
                .listing-select-wrapper__box
                  .listing-select-wrapper__box--select
                    = form.collection_select :category_id, category_grandchildren, :id, :name, prompt: "---"
                    .arrow-icon
                      = icon('fas', 'chevron-down', class: "arrow-icon")
        .form__content
          %h5.form__title
            ブランド
          %span.any__text
            任意
          .items-new__brand__main__name__form
            = form.text_field :brand, placeholder: "例）シャネル", class: "items-new__brand__main__name__form__bar"  
        .form__content
          %h5.form__title
            商品の状態
          %span.required__text
            必須
          .item_new_brand_text
            = form.collection_select :status, ItemStatus.all, :id, :status, prompt: "---"
            .arrow-icon
              = icon('fas', 'chevron-down', class: "arrow-icon")
        .form__delivery
          配送について
        .form__content
          %h5.form__title
            配送料の負担
          %span.required__text
            必須
        .item_new_brand_text
          = form.collection_select :delivery_fee, ItemDeliveryFee.all, :id, :payer, prompt: "---"
          .arrow-icon
            = icon('fas', 'chevron-down', class: "arrow-icon")
        .form__content
          %h5.form__title
            配送の方法
          %span.required__text
            必須
        .item_new_brand_text
          = form.collection_select :delivery_method, ItemDeliveryMethod.all, :id, :way, prompt: "---"
          .arrow-icon
            = icon('fas', 'chevron-down', class: "arrow-icon")
        .form__content
          %h5.form__title
            発送元の地域
          %span.required__text
            必須
        .item_new_brand_text
          = form.collection_select :delivery_from_location, ItemPrefecture.all, :id, :name, prompt: "---"
          .arrow-icon
            = icon('fas', 'chevron-down', class: "arrow-icon")
        .form__content
          %h5.form__title
            発送までの日数
          %span.required__text
            必須
        .item_new_brand_text
          = form.collection_select :preparation_day, ItemPreparationDay.all, :id, :days, prompt: "---"
          .arrow-icon
            = icon('fas', 'chevron-down', class: "arrow-icon")
        .form__price
          .form__price__head
            %h5.form__title
              販売価格
            %span.required__text
              必須
          .form__price__box
            %span.jpy__icon ¥
            = form.text_field :price, placeholder: "0", class: "items-new__brand__main__name__form__bar", id: "price-form"
        .fee
          販売手数料（10%）
        .profit
          %h1.profit__text 
            販売利益 
          .profit__price
            0円
        .submit-btn
          = form.submit "更新する", class: "exhibit-btn"
        .submit-btn
          = form.submit "下書きに保存", class: "draft-btn"
        .item__back
          = link_to "戻る", :back

app/views/items/_header.html.haml
.header
  .header__content
    .header__content__menu
      = link_to image_tag('logo.png',  height: '40px', width: '140px', class: 'header__content__menu__title'),root_path
      = form_with(url: "#", local: true, method: :get, class: "header__content__menu__search-form") do |form|
        .input-box
          = form.text_field :keyword, placeholder: "キーワードで探す", class: "input-box__form"
          %button{type: "submit",class: 'search-btn'}
            = image_tag 'icon-search 1.png',size: "20x20"
    .header__content__bottom
      .left-lists
        .left-lists__category
          = image_tag('icon_category.png', height: '20px', width: '20px', class: 'category')
          = link_to "カテゴリーから探す", '#', class: 'category-title'
        %ul.category-box
          %li.category-box__category-parent#category-parent-1
            = link_to "レディース", category_path(1), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-2
            = link_to " メンズ", category_path(2), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-3
            = link_to "ベビー・キッズ", category_path(3), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-4
            = link_to "インテリア・住まい・小物", category_path(4), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-5
            = link_to "本・音楽・ゲーム", category_path(5), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-6
            = link_to "おもちゃ・ホビー・グッズ", category_path(6), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-7
            = link_to "コスメ・香水・美容", category_path(7), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-8
            = link_to "家電・スマホ・カメラ", category_path(8), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-9
            = link_to "スポーツ・レジャー", category_path(9), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-10
            = link_to "ハンドメイド", category_path(10), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-11
            = link_to "チケット", category_path(11), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-12
            = link_to "自動車・オートバイ", category_path(12), class: "category-box__category-parent__link"
          %li.category-box__category-parent#category-parent-13
            = link_to "その他", category_path(13), class: "category-box__category-parent__link"
        .left-lists__brands
          = image_tag('icon_brand.png',height: '20px', width: '20px', class: 'brand')
          = link_to "ブランドから探す", '#',class: 'brand-title'
      .right-lists
        - if user_signed_in?
          .user-btn
            = link_to "マイページ", my_pages_path, class: 'mypage-link'
            = link_to "ログアウト", destroy_user_session_path, method: :delete , class: 'login-btn'
        - else
          .user-btn
            = link_to "新規会員登録", '/users/sign_up', class: 'signup-btn'
            = link_to "ログイン", '/users/sign_in', class: 'login-btn'

app/views/items/edit.html.haml
= render partial: "form", locals: { item: @item, item_images: @item_images, category_parent: @category_parent, category_child: @category_child, category_grandchild: @category_grandchild, category_parent_array: @category_parent_array, category_children: @category_children, category_grandchildren: @category_grandchildren }

app/views/items/index.html.haml
.main
  .menu1
    .menu1__content
      %h2.menu1__content__title 人生を変えるフリマアプリ
      %p.menu1__content__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .menu1__content__btn
        = link_to "#" do
          = image_tag('app-store-logo.svg', height: '80px', width: '180px', class: 'app-store-logo')
        = link_to "#" do
          = image_tag('google-play-logo.svg', height: '80px', width: '180px', class: 'google-play-logo')
  .menu2
    %h2.menu2__title FURIMAが選ばれる3つの理由
    %ul.menu2__lists
      %li.menu2__lists__list
        .menu2__lists__list__pict
          %span.number 1
          = image_tag('pict-reason-01.jpg', height: '300px', width: '300px')
        %h3.menu2__lists__list__title
          %span ３分
          ですぐに出品
        %p.menu2__lists__list__text スマホで入力するだけで簡単に出品できる！
      %li.menu2__lists__list
        .menu2__lists__list__pict
          %span.number 2
          = image_tag('pict-reason-02.jpg', height: '300px', width: '300px')
        %h3.menu2__lists__list__title
          %span シンプル
          で使いやすい
        %p.menu2__lists__list__text めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.menu2__lists__list
        .menu2__lists__list__pict
          %span.number 3
          = image_tag('pict-reason-03.jpg', height: '300px', width: '300px')
        %h3.menu2__lists__list__title
          手数料
          %span 業界最安
        %p.menu2__lists__list__text 最大3%でお得に出品&購入！

  .menu3
    .menu3__inner
      %h3.menu3__inner__title 会員数日本一位
      %p.menu3__inner__text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .menu1__content__btn
        = link_to "#" do
          = image_tag('app-store-logo.svg', height: '80px', width: '180px', class: 'app-store-logo')
        = link_to "#" do
          = image_tag('google-play-logo.svg', height: '80px', width: '180px', class: 'google-play-logo')
  .menu4
    %h2.menu4__title FURIMAの特徴
    .menu4__lists
      .menu4__lists__item
        = image_tag('icon-01.png', height: '260px', width: '169px')
        %h3.menu4__lists__item__title 簡単に売り買いできる
        %p.menu4__lists__item__text スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      .menu4__lists__item
        = image_tag('icon-03.png', height: '260px', width: '169px')
        %h3.menu4__lists__item__title 売上金は即日振込みに対応
        %p.menu4__lists__item__text 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      .menu4__lists__item
        = image_tag('icon-04.png', height: '260px', width: '169px')
        %h3.menu4__lists__item__title 様々な支払いに対応
        %p.menu4__lists__item__text お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  .menu5
    %h2.menu5__title ピックアップカテゴリー
    .menu5__item_box
      .menu5__item_box__title
        = link_to "新規投稿商品"
      .menu5__item_box__items
        = render partial: "category", locals: {items: @items}
  .menu5
    %h2.menu5__title ピックアップブランド
    .menu5__item_box
      .menu5__item_box__title
        = link_to "アーカイバ"
      .menu5__item_box__items
        = render partial: "brand", locals: {items: @items_brand}

    = link_to new_item_path, class: "sell-btn" do
      出品する
      = image_tag "icon_camera.png", size: "54x54", class: "camera-icon"

app/views/items/show.html.haml
.item__show
  .item__show__main
    .item__show__main__content
      .item__show__main__content__detail
        %h1.item__name 
          = @item.name
        .item__photo
          .item__photo__content
            .item__photo__content__detail
              - if @item.buyer_id.present?
                .sold-tag
                  .sold-tag__title sold out
              .item__photo__content__detail__main
                = image_tag "#{@image.image.url}", class: "owl__carousel__main show"
                - @images[1..9].each do |image|
                  = image_tag "#{image.image.url}", class: "owl__carousel__main"
          .item__photo__sub
            = image_tag "#{@image.image.url}", class: "owl__carousel__sub active"
            - @images[1..9].each do |image|
              = image_tag "#{image.image.url}", class: "owl__carousel__sub"
        .item__price
          %span.item__price__main
            = "¥#{@item.price}"
          .item__price__detail
            %span (税込)
            %span 送料込み
        - if user_signed_in? && !(current_user.id == @item.user_id) && !@item.buyer_id.present?
          .item__buy__btn
            = link_to "購入画面に進む", item_purchases_path(@item)
        .item__message
          = @item.item_explanation
        .item__table
          %table{border: "1"}
            %tr 
              %th 出品者
              %td 
                = link_to user_path(@item.user.id) do
                  = @item.user.nickname
                %br
                %i.fas.fa-laugh
                %span
                  - good_rates = UserRate.where(user_id: @item.user.id, rate: "good").length
                  = "#{good_rates}"
                %i.fas.fa-meh
                %span
                  - normal_rates = UserRate.where(user_id: @item.user.id, rate: "normal").length
                  = "#{normal_rates}"
                %i.fas.fa-frown
                %span
                  - bad_rates = UserRate.where(user_id: @item.user.id, rate: "bad").length
                  = "#{bad_rates}"
            %tr 
              %th カテゴリー
              %td
                = link_to "#" do
                  = @category_parent.name
                %br
                = link_to "#" do
                  = @category_child.name
                %br
                = link_to "#" do
                  = @category_grandchild.name
            %tr 
              %th ブランド
              %td
                - if @item.brand.present?
                  = link_to "#" do
                    = @item.brand
            %tr 
              %th 商品のサイズ
              %td
                - if @item.size.present?
                  = Size.find(@item.size_id).name
            %tr 
              %th 商品の状態
              %td
                = ItemStatus.find(@item.status).status
            %tr 
              %th 配送料の負担
              %td
                = ItemDeliveryFee.find(@item.delivery_fee).payer
            %tr 
              %th 配送の方法
              %td
                = ItemDeliveryMethod.find(@item.delivery_method).way
            %tr 
              %th 配送元地域
              %td 
                = ItemPrefecture.find(@item.delivery_from_location).name
            %tr 
              %th 発送日の目安
              %td
                = ItemPreparationDay.find(@item.preparation_day).days
        - if user_signed_in?
          .optional__area
            - if current_user.already_liked?(@item)
              = button_to like_path, params: {item_id: @item.id}, method: :delete do
                .heart__btn
                  %i.fas.fa-heart 
                  お気に入り
                  = @item.likes.count
            - else
              = button_to likes_path, params: {item_id: @item.id} do
                .heart__btn
                  %i.fas.fa-heart 
                  お気に入り
                  = @item.likes.count
            .flag__btn
              = link_to "#" do
                %i.fa.fa-flag
                不適切な商品の通報
      - if user_signed_in? && current_user.id == @item.user_id
        .item__show__main__content__box
          .box__my__btn
            = link_to "商品の編集", edit_item_path, class: "edit__btn"
            = link_to "この商品を削除する", item_path(@item.id), method: :delete, class: "delete__btn"
      .item__show__main__content__comment
        .comment__list
          - @comments.each do |comment| 
            .comment__list__content
              .comment__list__content__user
                = link_to user_path(comment.user_id), class: "user__nickname" do
                  = comment.user.nickname
                = link_to user_path(comment.user_id) do
                  - if comment.user.profile&.image.blank?
                    = image_tag "member_photo_noimage_thumb.png", class: "user__image"
                  - else
                    = image_tag "#{comment.user.profile.image.url}", class: "user__image"
              .comment__list__content__message
                = simple_format(comment.content)
                .comment__list__content__message__icons
                  %i.far.fa-clock
                  = time_ago_in_words(comment.created_at)
                  %p 前
        - if user_signed_in?
          .comment__form
            = form_with(model: [@item, @comment], local: "true") do |f|
              =f.text_area :content, class: "text__area"
              %p.notice__msg 
                相手のことを考え丁寧なコメントを心がけましょう。
                %br
                不快な言葉遣いなどは利用制限や退会処分となることがあります
              = f.button class: "comment__btn" do
                %i.fa.fa-comment コメントする
      .item__show__main__relatedeItems
        = link_to "#" do
          = "#{@category_parent.name}をもっと見る"